# Generated by Django 4.0.7 on 2022-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
